#!/bin/sh

LUAROCKS_SYSCONFDIR='/usr/local/etc/luarocks' exec '/usr/bin/lua5.2' -e 'package.path="/home/user01/dev/git/abc/lua/lua_modules/share/lua/5.2/?.lua;/home/user01/dev/git/abc/lua/lua_modules/share/lua/5.2/?/init.lua;/home/user01/.luarocks/share/lua/5.2/?.lua;/home/user01/.luarocks/share/lua/5.2/?/init.lua;/usr/local/share/lua/5.2/?.lua;/usr/local/share/lua/5.2/?/init.lua;"..package.path;package.cpath="/home/user01/dev/git/abc/lua/lua_modules/lib/lua/5.2/?.so;/home/user01/.luarocks/lib/lua/5.2/?.so;/usr/local/lib/lua/5.2/?.so;"..package.cpath' $([ "$*" ] || echo -i) "$@"
