[package]
name = "gwn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotpy = "1.0.0"


[[bin]]
name = "plot"
test = false
bench = false
path = "src/plot.rs"
